### PR TITLE
Fixed Makefile not working in Debian 11 & Fix pam_sm_setcred issue on Ubuntu 20.04

### LINKED ISSUE #11: Debian 11 (bullseye) undefined references to {SHA256,EVP,PKCS5}_*
After upgrading, I'm getting the following:
```
$ make -j$(nproc)
gcc -fPIC -fno-stack-protector -c -I/usr/local/ssl/include -DHASH_ROUNDS=1000 -DDB_PATH='"/usr/share/duress"' adduser.c
gcc -fPIC -fno-stack-protector -c -I/usr/local/ssl/include -DHASH_ROUNDS=1000 -DDB_PATH='"/usr/share/duress"' deluser.c
gcc -fPIC -fno-stack-protector -c -I/usr/local/ssl/include -DHASH_ROUNDS=1000 -DDB_PATH='"/usr/share/duress"' pam_duress.c
gcc -L/usr/local/ssl/lib -lcrypto deluser.o -o deluser
gcc -L/usr/local/ssl/lib -lcrypto adduser.o -o adduser
gcc -L/usr/local/ssl/lib -lcrypto -shared pam_duress.o -o pam_duress.so
/usr/bin/ld: deluser.o: in function `sha256hash':
deluser.c:(.text+0x75): undefined reference to `SHA256_Init'
/usr/bin/ld: deluser.c:(.text+0x97): undefined reference to `SHA256_Update'
/usr/bin/ld: deluser.c:(.text+0xaa): undefined reference to `SHA256_Final'
/usr/bin/ld: deluser.o: in function `pbkdf2hash':
deluser.c:(.text+0xc9): undefined reference to `EVP_sha256'
/usr/bin/ld: deluser.c:(.text+0x10a): undefined reference to `PKCS5_PBKDF2_HMAC'
collect2: error: ld returned 1 exit status
make: *** [Makefile:22: deluser] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: adduser.o: in function `sha256hash':
adduser.c:(.text+0x75): undefined reference to `SHA256_Init'
/usr/bin/ld: adduser.c:(.text+0x97): undefined reference to `SHA256_Update'
/usr/bin/ld: adduser.c:(.text+0xaa): undefined reference to `SHA256_Final'
/usr/bin/ld: adduser.o: in function `pbkdf2hash':
adduser.c:(.text+0xc9): undefined reference to `EVP_sha256'
/usr/bin/ld: adduser.c:(.text+0x10a): undefined reference to `PKCS5_PBKDF2_HMAC'
/usr/bin/ld: adduser.o: in function `genSalt':
adduser.c:(.text+0x141): undefined reference to `RAND_bytes'
/usr/bin/ld: adduser.o: in function `Encrypt':
adduser.c:(.text+0x1fa): undefined reference to `EVP_aes_256_cbc'
/usr/bin/ld: adduser.c:(.text+0x203): undefined reference to `EVP_sha256'
/usr/bin/ld: adduser.c:(.text+0x34e): undefined reference to `EVP_BytesToKey'
/usr/bin/ld: adduser.c:(.text+0x357): undefined reference to `EVP_CIPHER_CTX_new'
/usr/bin/ld: adduser.c:(.text+0x3b9): undefined reference to `EVP_CIPHER_CTX_reset'
/usr/bin/ld: adduser.c:(.text+0x3be): undefined reference to `EVP_aes_256_cbc'
/usr/bin/ld: adduser.c:(.text+0x3e0): undefined reference to `EVP_EncryptInit_ex'
/usr/bin/ld: adduser.c:(.text+0x40c): undefined reference to `EVP_EncryptUpdate'
/usr/bin/ld: adduser.c:(.text+0x43f): undefined reference to `EVP_CIPHER_CTX_free'
/usr/bin/ld: adduser.c:(.text+0x4d8): undefined reference to `EVP_EncryptFinal_ex'
/usr/bin/ld: adduser.c:(.text+0x50b): undefined reference to `EVP_CIPHER_CTX_free'
/usr/bin/ld: adduser.c:(.text+0x563): undefined reference to `EVP_CIPHER_CTX_free'
collect2: error: ld returned 1 exit status
make: *** [Makefile:18: adduser] Error 1
```

**libpam-dev** (`selecting 'libpam0g-dev' instead of 'libpam-dev'`) and **libssl-dev** are installed.

### LINKED ISSUE #16: Not working on Ubuntu 20.04
I'm testing it on a virtual machine. At the time of defining the module on the /etc/pam.d/common-auth file. 

I tried to add it like this:
```
# here are the per-package modules (the "Primary" block)
auth	[success=2 default=ignore]      pam_unix.so nullok_secure
auth    [success=1 default=ignore]      pam_duress.so allow
```
And is not working.

Trying `auth sufficient pam_duress.so` just broke my logins.

BTW: I have eCryptfs installed too.

### PR DESCRIPTION
**Pull request by Lqp1**
Fixes #11 and Fixes #16

### CODE REVIEW

**Comment by Lqp1** [comment]
I'm not 100% sure about the need to expose `pam_sm_setcred` tho. If someone has a good knowledge of PAM I would be happy to have more info about it :)

**Comment by Lqp1** [comment]
Hello @rafket , what do you think about this?
